-- PRE-PRODUCTION / LOCAL RECOVERY ONLY.
-- Production schema evolution remains forward/additive-first; do not use this script to erase live tenant data.
BEGIN;
DROP TABLE IF EXISTS workspace_readiness;
DROP TABLE IF EXISTS action_executions;
DROP TABLE IF EXISTS approval_requests;
DROP TABLE IF EXISTS action_plans;
DROP TABLE IF EXISTS usage_events;
DROP TABLE IF EXISTS evaluation_events;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS operational_events;
DROP TABLE IF EXISTS rule_conflicts;
ALTER TABLE IF EXISTS merchant_rules DROP CONSTRAINT IF EXISTS merchant_rules_current_version_fk;
DROP TABLE IF EXISTS merchant_rule_versions;
DROP TABLE IF EXISTS merchant_rules;
DROP TABLE IF EXISTS knowledge_items;
DROP TABLE IF EXISTS knowledge_sources;
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS fulfillments;
DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS inventory_observations;
DROP TABLE IF EXISTS variant_options;
DROP TABLE IF EXISTS variants;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS conversation_ownership_events;
DROP TABLE IF EXISTS message_drafts;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS customer_verification_events;
DROP TABLE IF EXISTS customer_identities;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS integration_capabilities;
DROP TABLE IF EXISTS integrations;
DROP TABLE IF EXISTS agency_client_assignments;
DROP TABLE IF EXISTS membership_roles;
DROP TABLE IF EXISTS memberships;
DROP TABLE IF EXISTS auth_organization_bindings;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS merchant_workspaces;
DROP TABLE IF EXISTS organizations;
COMMIT;
