import fs from 'node:fs';import path from 'node:path';
const t=JSON.parse(fs.readFileSync(path.join(process.cwd(),'release','COMMERCIAL_READY_E6_REVIEW_TEMPLATE_20260809.json'),'utf8'));
const clone=x=>JSON.parse(JSON.stringify(x));const assert=(x,m)=>{if(!x)throw new Error(m)};
const PR=['E6-PREREQ-01','E6-PREREQ-02','E6-PREREQ-03','E6-PREREQ-04','E6-PREREQ-05','E6-PREREQ-06','E6-PREREQ-07','E6-PREREQ-08'];
const SG=['E6-SIGNAL-01','E6-SIGNAL-02','E6-SIGNAL-03','E6-SIGNAL-04','E6-SIGNAL-05'];
const RV=['E6-REVIEW-01','E6-REVIEW-02','E6-REVIEW-03','E6-REVIEW-04','E6-REVIEW-05','E6-REVIEW-06','E6-REVIEW-07'];
const REF_KEYS=['requirements_coverage_ref','pass_fail_blocked_summary_ref','provider_capabilities_last_verified_ref','security_privacy_results_ref','migration_rollback_status_ref','known_issues_ref','incident_regression_ref','usage_cost_changes_ref','ux_language_evaluation_ref','owner_approvals_ref','release_rollback_steps_ref'];
function errors(x){const e=[];if(x.target_maturity!=='E6_COMMERCIAL_READY_PASS'||x.release_target!=='COMMERCIAL_READY')e.push('TARGET');if(x.secrets_or_customer_pii_allowed!==false)e.push('SECRET');for(const id of PR)if(!x.prerequisite_evidence?.some(y=>y.id===id))e.push('PR:'+id);for(const id of SG)if(!x.commercial_signals?.some(y=>y.id===id))e.push('SG:'+id);for(const id of RV)if(!x.release_board_questions?.some(y=>y.id===id))e.push('RV:'+id);for(const y of [...(x.prerequisite_evidence??[]),...(x.commercial_signals??[])]){if(!Array.isArray(y.evidence_refs))e.push('REFS:'+y.id)}for(const y of x.release_board_questions??[])if(!Array.isArray(y.evidence_refs))e.push('REFS:'+y.id);return e}
function canE6(x){if(errors(x).length)return false;if(!x.review_identity?.commercial_review_ref)return false;if(!x.prerequisite_evidence.every(y=>y.state==='PASS'&&y.evidence_refs.length))return false;if(!x.commercial_signals.every(y=>y.state==='PASS'&&y.evidence_refs.length))return false;if(!x.release_board_questions.every(y=>y.decision==='YES'&&y.evidence_refs.length))return false;if(!REF_KEYS.every(k=>x.release_candidate_pack_refs?.[k]))return false;const r=x.e6_evidence_record_projection;if(!r||r.resultState!=='PASS'||r.maturity!=='E6_COMMERCIAL_READY_PASS'||!r.requirementIds?.includes('CRV1-COMMERCIAL-READY')||!r.evidenceRefs?.length||!r.providerRef||!r.exactOperationRef||!r.authEvidenceRef||!r.dogfoodRef||!r.designPartnerRef||!r.commercialGateRefs?.length)return false;return true}
function passing(){const x=clone(t);x.overall_state='PASS';x.review_identity.commercial_review_ref='commercial-review:safe';for(const y of x.prerequisite_evidence){y.state='PASS';y.evidence_refs=[`evidence:${y.id}`]}for(const y of x.commercial_signals){y.state='PASS';y.evidence_refs=[`evidence:${y.id}`]}for(const y of x.release_board_questions){y.decision='YES';y.evidence_refs=[`evidence:${y.id}`]}for(const k of REF_KEYS)x.release_candidate_pack_refs[k]=`ref:${k}`;Object.assign(x.e6_evidence_record_projection,{resultState:'PASS',evidenceRefs:['evidence:e6'],providerRef:'provider:safe',exactOperationRef:'ops:safe',authEvidenceRef:'auth:safe',dogfoodRef:'dogfood:safe',designPartnerRef:'partner:safe',commercialGateRefs:['commercial-review:safe']});return x}
const c=[];c.push(['STRUCTURE',()=>assert(!errors(t).length,errors(t).join(','))]);c.push(['DEFAULT-NOT-RUN',()=>assert(t.overall_state==='NOT_RUN'&&!canE6(t),'auto')]);c.push(['NO-PII-SECRETS',()=>assert(!t.secrets_or_customer_pii_allowed,'secret')]);c.push(['PREREQS-COMPLETE',()=>assert(PR.every(id=>t.prerequisite_evidence.some(x=>x.id===id)),'pr')]);c.push(['SIGNALS-COMPLETE',()=>assert(SG.every(id=>t.commercial_signals.some(x=>x.id===id)),'sg')]);c.push(['REVIEW-QUESTIONS-COMPLETE',()=>assert(RV.every(id=>t.release_board_questions.some(x=>x.id===id)),'rv')]);
const m1=clone(t);m1.commercial_signals=m1.commercial_signals.filter(x=>x.id!=='E6-SIGNAL-01');c.push(['WTP-SIGNAL-MISSING-FAILS',()=>assert(errors(m1).some(x=>x.startsWith('SG:')),'wtp')]);const m2=clone(t);m2.release_board_questions=m2.release_board_questions.filter(x=>x.id!=='E6-REVIEW-05');c.push(['ECONOMICS-REVIEW-MISSING-FAILS',()=>assert(errors(m2).some(x=>x.startsWith('RV:')),'econ')]);
const prose=clone(t);prose.e6_evidence_record_projection.resultState='PASS';c.push(['PROSE-ONLY-PASS-FAILS',()=>assert(!canE6(prose),'prose')]);const p=passing();c.push(['FULL-E6-CAN-PROJECT',()=>assert(canE6(p),'full')]);
for(const k of ['commercial_review_ref']){const x=passing();x.review_identity[k]=null;c.push(['MISSING-COMMERCIAL-REVIEW-FAILS',()=>assert(!canE6(x),'review')])}
for(const k of ['providerRef','exactOperationRef','authEvidenceRef','dogfoodRef','designPartnerRef']){const x=passing();x.e6_evidence_record_projection[k]=null;c.push([`MISSING-${k.toUpperCase()}-FAILS`,()=>assert(!canE6(x),k)])}
const cg=passing();cg.e6_evidence_record_projection.commercialGateRefs=[];c.push(['MISSING-COMMERCIAL-GATE-REFS-FAILS',()=>assert(!canE6(cg),'cg')]);const noWtp=passing();noWtp.commercial_signals[0].state='NOT_RUN';c.push(['WTP-NOT-RUN-BLOCKS',()=>assert(!canE6(noWtp),'wtp')]);const noRet=passing();noRet.commercial_signals[2].evidence_refs=[];c.push(['RETENTION-EVIDENCE-MISSING-BLOCKS',()=>assert(!canE6(noRet),'ret')]);const noQ=passing();noQ.release_board_questions[5].decision='NO';c.push(['REVIEW-NO-BLOCKS',()=>assert(!canE6(noQ),'no')]);const noPack=passing();noPack.release_candidate_pack_refs.known_issues_ref=null;c.push(['INCOMPLETE-RELEASE-PACK-BLOCKS',()=>assert(!canE6(noPack),'pack')]);c.push(['E5-NOT-SUFFICIENT-BY-ITSELF',()=>assert(t.promotion_rules.e6_pass_cannot_be_inferred_from_e5_or_ui===true,'maturity')]);
let n=0;for(const [name,fn] of c){fn();n++;console.log('PASS '+name)}console.log(`PASS ${n}/${c.length} commercial-ready E6 review template scenarios`);
